data:
  trainpath: /mounts/Datasets3/2024-2025-ChallengePlankton/train
  testpath: /mounts/Datasets3/2024-2025-ChallengePlankton/test
  batch_size: 4
  num_workers: 8
  valid_ratio: 0.2
  patch_size: 128

optim:
  algo: AdamW
  params:
    lr: 0.0001
    weight_decay: 0.01
    # betas: [0.8, 0.9]
    # momentum: 0.9


nepochs: 100
loss: 
  name: DiceFocalLoss
  params:
     alpha: [.2, .8]
     gamma: 2.5
     dice_weight: .2
     focal_weight: .8


logging:
  wandb: 
    project: planktonDL
    entity: idris-dhaou
  logdir: "/usr/users/sdim/sdim_15/model_logs"  # Better to provide the fullpath, especially on the cluster

model:
  class: UnetPlus
  threshold: .55

prediction:
  #dir: "/usr/users/sdim/sdim_15/prediction




