data:
  trainpath: /mounts/Datasets3/2024-2025-ChallengePlankton/train
  testpath: /mounts/Datasets3/2024-2025-ChallengePlankton/test
  batch_size: 4
  num_workers: 8
  valid_ratio: 0.2
  patch_size: 128

optim:
  algo: Adam
  params:
    lr: 0.001

nepochs: 100
loss: 
  name: "CrossEntropyLoss"
  params:

logging:
  # wandb: 
  #   project: sample_project
  #   entity: sample_entity
  logdir: "/usr/users/sdim/sdim_15/project_plankton  # Better to provide the fullpath, especially on the cluster

model:
  class: Vanilla
  num_layers: 4


